- name: Copying index file
  hosts: all 
  become: yes
  tasks:
    - name: create index.html file
      copy:
        src: /var/lib/jenkins/workspace/job6/index.html       
        dest: /var/www/html/index.html
        force: yes
