- name: Test
  hosts: all 
  become: yes
  tasks:
    - name: Install apache
      apt:
        name: apache2
        state: latest
    - name: start the service
      service:
        name: apache2
        state: started
    - name: create index.html file
      copy:
        content: "hi from Yogesh Jenkins"
        dest: /var/www/html/index.html
        force: yes
